### ISSUE TITLE
Name conflict with built-in package

### ISSUE THREAD

**Issue by tarsius** [toroidal-code/dom.el#2]
Starting with `v25.1` Emacs contains a library named `dom.el`. Even though your library is older than this new implementation, I don't think you have much of a choice but to rename your library. Or maybe you can now deprecate your implementation in favor of this new one?

There currently exists one package on Melpa which appears to depend on you `dom` implementation: `showcss-mode`. (Which looks quite nice by the way.) @8cylinder could you please consider porting your package to use the built-in `dom`? Or if that isn't feasible, then help @toroidal-code picking another name and make the transition.

@purcell What should be done on Melpa about this?

For the time being the Emacsmirror does not mirror `showcss-mode`. And the (yet to be released) database contains information about the built-in `dom`.

**Comment by purcell** [comment]
Yes, we'll have to remove this from MELPA if it's going to clash with a built-in package.

**Comment by 8cylinder** [comment]
Thanks for the heads up @tarsius.  Where can I get more info about the new built in `dom`?

**Comment by tarsius** [comment]
Here it is: https://github.com/jwiegley/emacs/blob/emacs-25/lisp/dom.el.

**Comment by purcell** [comment]
Will there be an ELPA-hosted version of this, then? I hope so, otherwise `showcss-mode` is going to end up requiring Emacs 25.1.

**Comment by 8cylinder** [comment]
My (purely selfish) preference is that this library would get renamed to something else and continue to be available as a dependency.  All I would have to do, is update my code to point to the new name.

There doesn't seem to be any documentation for the new dom.el and without that I'm pretty much lost, and looking through the code, there doesn't appear to be anyway to parse a document.  I'm just guessing, but that looks like it happens somewhere else.

Also, even if I do manage to port it, I don't know how I would handle pre Emacs 25.1 versions.

Until some documentation for the new dom.el comes along, I'll hope for a new name or if that doesn't work, I can distribute this dom.el with the showcss package.

**Comment by purcell** [comment]
> My (purely selfish) preference is that this library would get renamed to something else and continue to be available as a dependency. All I would have to do, is update my code to point to the new name.

That would be a good outcome.

>  or if that doesn't work, I can distribute this dom.el with the showcss package.

Please don't do that without renaming it first -- otherwise, installing your package would lead to the built-in `dom.el` being shadowed by your bundled version.

**Comment by 8cylinder** [comment]
What is the approximate time line for removing this package if it doesn't change its name?

**Comment by tarsius** [comment]
Because third-party packages don't stand a change when their names conflict with a built-in package, it is doomed. I therefore propose that it be renamed to `domed.el`.

**Comment by purcell** [comment]
Yep, I'd plan to remove it pretty soon. We can't have it interfering with people's built-in packages.

**Comment by tarsius** [comment]
@toroidal-code isn't the original author and since she is not replying I think it would be okay to just add this to the [orphanage](https://github.com/emacsorphanage) and make the necessary adjustments there.

I can do that myself but would like some input on a new name `domed`, `doomed`, or something else?

**Comment by tarsius** [comment]
@8cylinder @purcell I have renamed `dom.el` to `doom.el` and made the result available [from the orphanage](https://github.com/emacsorphanage/doom).

I have also adjusted `show-css` https://github.com/8cylinder/showcss-mode/pull/7 and the recipe https://github.com/milkypostman/melpa/pull/3514.

**Comment by tarsius** [comment]
Since nothing depends on this package anymore (as far as I know), I am closing this now.

**Comment by tarsius** [comment]
I am trying to reduce the number of special cases I have to deal with in my work on the Emacsmirror. 

@8cylinder since your `show-css` is the only dependant and the author has shown little interest in keeping `dom`/`doom` compatible with recent Emacsen, would you be willing to put `doom` on your github account? Just fork it from the [orphanage](https://github.com/emacsorphanage) and tell me. I will do the rest (i.e. update Melpa and Emacsmirror).

@toroidal-code Of course if you would be willing to host and maintain the renamed version, then that would be best.
